### ISSUE TITLE
Traceback on Ubuntu 18.04 with LANG set to es_PY.utf8

### ISSUE THREAD

**Issue by quozl** [sugarlabs/speak#23]
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 219, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 50, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Speak.activity/activity.py", line 204, in __init__
    self.face = face.View(fill_color=lighter)
  File "/usr/share/sugar/activities/Speak.activity/face.py", line 120, in __init__
    self.status = Status()
  File "/usr/share/sugar/activities/Speak.activity/face.py", line 57, in __init__
    self.voice = voice.defaultVoice()
  File "/usr/share/sugar/activities/Speak.activity/voice.py", line 138, in defaultVoice
    voices = allVoices()
  File "/usr/share/sugar/activities/Speak.activity/voice.py", line 117, in allVoices
    _allVoices['English'] = _allVoices['English (America)']
KeyError: 'English (America)'
```

Caused by https://github.com/sugarlabs/speak/commit/72d6ff14ad54b32828c971317221316dd19cef23.

**Comment by tchx84** [comment]
This is fixed by https://github.com/sugarlabs/speak/pull/29

**Comment by quozl** [comment]
Thanks.  Merged.

**Comment by Kiy4h** [comment]
Should this GCI task be deleted? https://codein.withgoogle.com/tasks/5372853315174400/

**Comment by quozl** [comment]
Thanks, yes.  I can't delete, but @walterbender can.  I've set instance count zero.
